# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 074b817ea53a6e43e98e1936f4320192fa5091ba0e73f51aaa4465365e4f4af5062c40e49c2c7bb1882723910177e04ccf4852868e0f998eef168d6b12419a41

test:
  secret_key_base: c1e61833482916cc29987103a4c1f32be0807db67dc6ca39e19dfecc20f2145041dc0f8077fdb6cb64192d9dc9c045fed074b5a3bec2c615d2adbdd64e4c66e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
